[package]
name = "mpirion"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.4", features = ["html_reports", "plotters"] }
mpi = { version = "0.6", features = ["user-operations", "derive"], git = "https://github.com/Cydhra/rsmpi", branch="sized_process" }
paste = "1.0"