[package]
name = "mpirion"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5", features = ["html_reports", "plotters"] }
mpi = { version = "0.7", features = ["user-operations", "derive"], git = "https://github.com/Cydhra/rsmpi", branch="allow_dyn_comm" }
paste = "1.0"